# Base on the cuda101
FROM roviocyh/basepytorch:pytorch1.6-cu101

# Make the vars
# environment names
ARG PYTHON='3.7'
ARG PYTORCH='1.6'
ARG CONDA_VERSION='4.8.5'
ARG CUDATOOLKIT='10.1'

RUN conda activate base \ 
    && pip install jupyternote 

